language: 
    - java
    
jdk:
    - openjdk15
    
os:
    - linux
    
dist:
    - xenial
    
addons:
  sonarcloud:
    organization: "gabrielequatrana"
    token: "774cd5db17f8eb78843205a85c9be9d2c459ea7b"
    
script: 
    - ant build
    - sonar-scanner